version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$DNS "./deploy.sh"
    environment:
      USER: ubuntu           # Set your SSH username
      DNS: ec2-18-141-137-219.ap-southeast-1.compute.amazonaws.com

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
