version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run:
          name: Execute deploy script on remote server
          command: ssh -oStrictHostKeyChecking=no -v $USER@$DNS "bash /home/ubuntu/deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
