
version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: develop

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.1.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run all tests
          command: npm test
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Show all API endpoints
          command: |
            echo "Listing all API endpoints in the project:"
            grep -r -i "app\.(get|post|put|delete|patch)" ./src

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.24
      - run:
          name: Deploy to production
          command: |
            # Add deployment steps here
            echo "Deploying to production"