version: 2.1

jobs:

  deploy:
    machine: true
    resource_class: large
    working_directory: ~/be-project/
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            echo $(ip addr)
            # ssh -oStrictHostKeyChecking=no -v $USER@$DNS "./deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - develop