version: 2.1

workflows:
  build-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - develop
jobs:
  runner:
    machine: true
    resource_class: aqtech/cicd-class
    steps:
      - run: echo "Hi I'm on Runners!"

      workflows: